# PostgreSQL Table Definitions

UNITS_TABLE_CREATE = """
CREATE TABLE IF NOT EXISTS units (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    location VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
"""

SENSOR_DATA_TABLE_CREATE = """
CREATE TABLE IF NOT EXISTS sensor_data (
    id UUID PRIMARY KEY,
    unit_id UUID REFERENCES units(id) ON DELETE CASCADE,
    timestamp TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    temperature NUMERIC,
    humidity NUMERIC,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    is_archived BOOLEAN NOT NULL DEFAULT FALSE
);
"""
